### ISSUE TITLE
minilibx_mms_20200219_beta 라이브러리 사용 시 라이브러리가 로딩되지 않음.

### ISSUE THREAD

**Issue by ykoh42** [humblEgo/cub3D_map_tester#3]
안녕하세요!

좋은 테스터를 제공해주셔서 감사합니다!

테스터를 사용하면서 약간(?) 개선되었으면 하는 점을 제보 드려요!

제가 능력이 있다면 코드로 작성해서 pr했겠지만,,, 실력 부족으로 제보만 드립니다..😭

minilibx_mms_20200219_beta 라이브러리를 사용하면 프로그램을 실행하는 경로에 libmlx.dylib 라이브러리가 있어야 하는 모양입니다. 

```
dyld: Library not loaded: libmlx.dylib
  Referenced from: /Users/ykoh/Desktop/42cursus/cub3d/cub3D_map_tester/../cub3D
  Reason: image not found
./test_map_valid_function.sh: line 132: 84078 Abort trap: 6           ${CUB3D} ${MAPS_FOLDER}${TEST_MAP}
```

이런 오류가 나타납니다!

**Comment by ykoh42** [comment]
근데 저만 이런 현상이 나타나는 것일 수도 있는데.. 다른 mms 라이브러리를 사용하시는 분들의 의견도 들어봐야할 것같아요 ㅠㅠ..

**Comment by humblEgo** [comment]
제보 감사합니다! 해당 이슈 관련하여 PR 날려주신 것 확인하여 코멘트 남겨드렸어요 :)
